#!/bin/bash

MSG="$1"

echo "commit-msg: check the commit message..."

if [ "$MSG" = ".git/COMMIT_EDITMSG" ]; then
  echo "commit-msg: extract commit message from .git/COMMIT_EDITMSG"
  MSG=`cat .git/COMMIT_EDITMSG`
fi

echo $MSG

if ! (echo "$MSG" | grep -Eq "^#[0-9]+");then
    echo "ERROR! Your commit message must contain task number at the beginning, e.g. '#13 do something'"
    exit 1
else
    echo "commit-msg: dear developer, commit message format is okay"
fi
